title: urg.systems
email: greg@urg.systems
description: >-
  Infrastructure notes, lab experiments, and real-world postmortems. No fluff.
baseurl: "" 
url: "https://urg.systems"
author: G

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Show excerpts on the homepage
excerpt_separator: <!--more-->

# Clean up unnecessary metadata defaults
twitter_username: ""
github_username: ""

# Optional: clean up default output
exclude:
  - README.md
  - node_modules/
  - vendor/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

